[package]
name = "assignment_0"
version = "0.1.0"
authors = ["Shakaib-Naqvi <shakaibnaqvi401@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.5"
text_io = "0.1.8"